name: void
favicon: null
layout_spectrum: 0.8067657328210771
typography_spectrum: 0.8675929585006088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.7021508074831218
purpose:
  - name: shares
    item: null
    url: null
